name = "AbstractNetworks"
uuid = "60874f82-5ada-4c70-bd1c-fa6be7711c8a"
authors = ["Michael Kraus"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
